Add point value import page
infiniteautomation/ma-dashboards pull request #375
Opened 2021-02-24 16:31 UTC by MertCingoz

2021-02-24 21:56 UTC, jazdw requested changes
Only some small changes, all in all it looks very good. The drop area does not seem to work on Chrome, what browser did you test in?

2021-02-24 21:56 UTC, jazdw commented on UI/resources/i18n.properties
> +ui.dox.pointValueImport= Point value import
Extra space

2021-02-24 21:56 UTC, jazdw commented on UI/web-src/ngMango/components/pointValueImport/pointValueImport.js
> +                this.error = (err.data && err.data.cause) || err.mangoStatusText;
Cause is only available to superadmin, just use mangoStatusText

2021-02-24 21:56 UTC, jazdw commented on UI/web-src/ngMango/services/pointValueModification.js
> +            static import(file, params) {
Can you move this to the maPointValues service

2021-02-24 21:57 UTC, jazdw commented
Including screenshots for @terrypacker @Joelhaggar to review

Download CSV from watchlist page (already existed, including for reference)
![image](https://user-images.githubusercontent.com/3579645/109071027-7c7fbd00-76b0-11eb-9166-1f8815151076.png)

Link on admin home -
![image](https://user-images.githubusercontent.com/3579645/109071142-94efd780-76b0-11eb-911b-b08753d0e0cf.png)

Page appearance -
![image](https://user-images.githubusercontent.com/3579645/109071154-9c16e580-76b0-11eb-93d0-34de6d1b2073.png)

Feedback (error is legitimate) -
![image](https://user-images.githubusercontent.com/3579645/109071205-a89b3e00-76b0-11eb-8ead-533535702265.png)

2021-02-25 15:49 UTC, MertCingoz commented
> Only some small changes, all in all it looks very good. The drop area does not seem to work on Chrome, what browser did you test in?

I am testing with Chrome and Firefox , both works with drop area for me
Chrome version 88.0.4324.190 (Official Build) (64-bit)
Firefox version 86.0 (64 bit)

2021-02-25 16:18 UTC, jazdw commented
Looks like .csv files have a different MIME type on my machine since I have Excel installed
![image](https://user-images.githubusercontent.com/3579645/109182374-22cbd100-774a-11eb-83d3-7adb1d2565f4.png)

Maybe just check the file extension only?

2021-02-25 17:50 UTC, MertCingoz commented
I have found possible mime types for a csv file and changed the code to accept these

```
  'application/csv',
  'application/x-csv',
  'application/vnd.ms-excel',
  'text/csv',
  'text/x-csv',
  'text/comma-separated-values',
  'text/x-comma-separated-values'
```

2021-02-25 20:36 UTC, merged